// CPG Explorer — HTTP API server for the Code Property Graph database.
//
// Serves a read-only REST API over the SQLite CPG database generated by cpg-gen.
// Designed for the React frontend; all responses are JSON.
package main

import (
	"context"
	"flag"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"cpg-explorer/internal/db"
	"cpg-explorer/internal/handler"
	"cpg-explorer/internal/middleware"
)

func main() {
	dbPath := flag.String("db", envOrDefault("DB_PATH", "cpg.db"), "Path to CPG SQLite database")
	addr := flag.String("addr", envOrDefault("ADDR", ":8080"), "HTTP listen address")
	flag.Parse()

	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	slog.SetDefault(logger)

	database, err := db.Open(*dbPath)
	if err != nil {
		slog.Error("failed to open database", "path", *dbPath, "error", err)
		os.Exit(1)
	}
	defer database.Close()

	h := handler.New(database)

	mux := http.NewServeMux()
	h.Register(mux)

	srv := &http.Server{
		Addr:         *addr,
		Handler:      middleware.Chain(mux, middleware.CORS, middleware.Logger, middleware.Recovery),
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 120 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Start server in a goroutine for graceful shutdown.
	go func() {
		slog.Info("starting CPG Explorer API", "addr", *addr, "db", *dbPath)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	// Block until SIGINT or SIGTERM.
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	slog.Info("shutting down server...")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		slog.Error("shutdown error", "error", err)
	}
	slog.Info("server stopped")
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
